### PR TITLE
Feat: Add JCasC support

### PR DESCRIPTION
**Pull request by topikachu**
1. Add JCasC Configurator
2. Add JCasC test
3. Covert all tests to use Jenkins rule instead of HudsonTestCase
4. Upgrade snakeyaml-api and jackson2-api plugin version required by JCasC plugin

E2E test in an Jenkins instance

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by topikachu** [comment]
@johnou 
Could you take a look at this change?
I'd like to add Jenkins Configuration as Code so I can config when creating a new Jenkins intance.

**Comment by topikachu** [comment]
@johannol 
I'd like to add JCasC to this plugin, so I can config the backup plan for multiple Jenkins instances from the configuration.
Could you review this change? 
Thanks

**Comment by johnou** [comment]
Will review when I return from vacation.

**Comment by topikachu** [comment]
> Will review when I return from vacation.

Have a good day. Sir ^-^

**Comment by topikachu** [comment]
@johnou  Hope you have a happy vacation. Could you take a look at this change when have time?

**Comment by xabinapal** [comment]
This is interesting and, considering the goal of this plugin, completely necessary to ensure deployments of Jenkins instances are 100% repeatable without manual intervention, as part of a disaster recovery procedure.

**Review by johnou — APPROVED** [review]

**Comment by johnou** [comment]
@topikachu thanks!

**Comment by topikachu** [comment]
@johnou  Could you release a new version?

**Comment by topikachu** [comment]
@johnou Could you release a new version?

Any idea?

**Comment by TaiSHiNet** [comment]
@johnou any chance we can get this released so @topikachu's changes go in? 

Much appreciated to you both!

**Comment by uhafner** [comment]
@johnou Do you need help with creating a new release? If you don't have the time anymore and want to mark the plugin for adoption please follow our process here: https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by johnou** [comment]
sorry for dropping the ball here, missed the notifications. I am working on getting a release out this week, unfortunately some issues with the JCasC test on Windows, I just pushed a work around with updating the dependencies see https://github.com/jenkinsci/periodicbackup-plugin/pull/23/files#diff-6bf0a50599d68f4f92443a92980595444c9f78aacc4ae80ce67e6ec3433690c7R46

**Comment by johnou** [comment]
2.0 released, thanks for the contribution!

**Comment by TaiSHiNet** [comment]
Thank you for all the hard work!

**Pull request merged**
